"""empty message

Revision ID: 69b0dfac961d
Revises: c098363070ef
Create Date: 2023-04-09 22:34:30.614081

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "69b0dfac961d"
down_revision = "c098363070ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("IN", "OUT", name="transactiontypeenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    # ### end Alembic commands ###
