"""empty message

Revision ID: 823cf0d445ae
Revises: 69b0dfac961d
Create Date: 2023-04-10 22:52:17.573390

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "823cf0d445ae"
down_revision = "69b0dfac961d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("account_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transaction", "account", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "account_id")
    # ### end Alembic commands ###
